channels:
  - conda-forge
  - defaults # anaconda
  - pytorch
dependencies:
  - conda-forge::ncurses # fixes: libtinfo.so.6: no version information available (required by bash)
  - ipykernel # vscode jupyter notebook
  - ipython # vscode jupyter notebook
  - notebook # jupyter notebook
  - pandas # vscode
  - pytorch::pytorch
  - pytorch::torchaudio # pytorch
  - pytorch::torchvision # pytorch
  - python>=3.9 # ?
  #- libgcc-ng #>=11.2.0 # pytorch
  - pip
  # - pip: